install.packages("readxl")
library("readxl")
book <- read.csv(file.choose())
View(book)
install.packages("arules")
library("arules")
install.packages("arulesViz")
library("arulesViz")
arules <- apriori(as.matrix(book,parameter = list(support=0.002,confidence=0.6)))
inspect(arules)
inspect(sort(arules,by="lift"))
plot(arules)
plot(arules,method="grouped")
plot(arules[1:5],method="grouped")
