install.packages("readxl")
library("readxl")
Groceries <- read.csv(file.choose())
View(Groceries)
install.packages("arules")
library("arules")
install.packages("arulesViz")
library("arulesViz")
arules <- apriori(Groceries,parameter = list(support=0.002,confidence=0.6))
inspect(arules)
inspect(head(sort(arules,by="lift")))
plot(arules)
plot(arules,method="grouped")
plot(arules[1:10],method="grouped")
