install.packages("readxl")
library("readxl")
my_movies <- read.csv(file.choose())
View(my_movies)
test <- my_movies[,-1:-5]
View(test)
install.packages("arules")
library("arules")
install.packages("arulesViz")
library("arulesViz")
arules <- apriori(as.matrix(test,parameter = list(support=0.002,confidence=0.6)))
inspect(arules)
inspect(head(sort(arules,by="lift")))
plot(arules)
plot(arules,method="grouped")
plot(arules[1:9],method="grouped")
